<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net462;net8.0-windows;net10.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>false</SignAssembly>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Samples\Zoombox\Resources\ZoomboxProperties.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Samples\Zoombox\Resources\ZoomboxProperties.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Xceed.Wpf.Samples.SampleData">
      <HintPath>..\..\Libs\Xceed.Wpf.Samples.SampleData.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xceed.Wpf.Toolkit\DotNetProjects.Wpf.Extended.Toolkit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="App.ico" />
  </ItemGroup>
</Project>